### ISSUE TITLE
Mistake in example code

### ISSUE THREAD

**Issue by Bartvelp** [UncleRus/esp-idf-speex#1]
Hi, thanks for your code.
In the sample encode code you speficy a encoder state by calling decoder_init, this doesn't work. I figured this out after a day of debugging.
https://github.com/UncleRus/esp-idf-speex/blob/24a8b64fb0a3130e69758efc5960016d598ff481/examples/encode_file/main/main.c#L24
Line should read:
```c
  void *encoder_state = speex_encoder_init(&speex_nb_mode);
```

Thanks for the library, very helpfull

**Comment by arpit-softcircuits** [comment]
> Hi, thanks for your code. In the sample encode code you speficy a encoder state by calling decoder_init, this doesn't work. I figured this out after a day of debugging.
> 
> https://github.com/UncleRus/esp-idf-speex/blob/24a8b64fb0a3130e69758efc5960016d598ff481/examples/encode_file/main/main.c#L24
> 
> 
> Line should read:
> ```c
>   void *encoder_state = speex_encoder_init(&speex_nb_mode);
> ```
> 
> Thanks for the library, very helpfull

hi Bartvelp ,  were you able to use this library with satisfactory result?

**Comment by Bartvelp** [comment]
> hi Bartvelp , were you able to use this library with satisfactory result?

Yes, I was other than a few kinks here and there the library is just an old version of the speex source code and works like a charm

**Comment by arpit-softcircuits** [comment]
thanks for reply. i have a main doubt that how to define frame size ?

**Comment by Bartvelp** [comment]
> thanks for reply. i have a main doubt that how to define frame size ?

I don't really understand what you mean Arpit. Frame size is calculated based on the band (wideband or narrowband) and the quality. For example setting the band to wideband and quality 2 like this:
```c++
    encoder_state = speex_encoder_init(&speex_wb_mode);
    uint32_t quality = 2;
    speex_encoder_ctl(encoder_state, SPEEX_SET_QUALITY, &quality);
```

Will give you a bitrate of `7500` according to https://speex.org/docs/manual/speex-manual/node11.html#SECTION001140000000000000000
and has a framesize of 20, if I remember correctly.

I would higly recommend giving the speex manual a look, because as I said, this library is mostly just and old version of the source code.
https://speex.org/docs/manual/speex-manual/

You can read the frame size of an encoder or decoder like this:
```c++
    // Get frame size
    uint32_t frame_size = 0;
    speex_encoder_ctl(encoder_state, SPEEX_GET_FRAME_SIZE, &frame_size);
    Serial.println("Encoder Frame_size: " + String(frame_size));
```
